### ISSUE TITLE
请问，既然go frame主库迁移到github了，那么gkvdb是否也会做相应的迁移和依赖修改呢？

### ISSUE THREAD

**Issue by praynise** [johng-cn/gkvdb#3]
请问，既然go frame主库迁移到github了，那么gkvdb是否也会做相应的迁移和依赖修改呢。目前来看，gkvdb中的依赖包应该还是gitee链接

**Comment by gqcn** [comment]
@praynise 会，但是优先级不高，后面发新版本会修改，近期内暂时没有新版本的计划。

**Comment by gqcn** [comment]
@praynise 已更新。

**Comment by praynise** [comment]
谢谢
